### ISSUE TITLE
As an 18F team member, I'd like to have clear,  well-balanced, and up- to-date responsibilities

### ISSUE THREAD

**Issue by christophermather** [18F/usfs-special-uses-prototype#28]
```[tasklist]
### Tasks
- [x] Set up re-chartering exercise w/ team
- [x] Do re-chartering exercise
- [x] Delegate responsibilities
- [x] Set up any new automations and/or reminders
```
