### ISSUE TITLE
EPIC: As a permit seeker, I want to to know what the application process looks like up front (including steps and how long it might take, and what I'll need to have/know), so that I can evaluate whether pursuing a  permit is worth my time

### ISSUE THREAD

**Issue by dluetger** [18F/usfs-special-uses-prototype#76]
This is an epic to capture "starting at the start" for our SF299 wizard, explainer content helping permit seekers plan and gather their materials.
```[tasklist]
### Tasks
- [ ] Design page layout for explainer page
- [ ] Implement web page
- [ ] Write content for "how long might this take"
- [ ] Write content for "what materials should I gather?"
- [ ] Write content for "what steps should I expect?"
```

**Comment by christophermather** [comment]
From prior brainstorming: 

What is valuable about our mockup landing page?

As a proponent I want to install fiber optic cable across FS lands so that I can provide internet service to unserved users.

As a proponent I want to get a special use permit so that I can install fiber optic cable ...

As a proponent, I want to submit a proposal for a permit so that I can get a permit.

As a proponent, I want to know what information is part of a proposal so that I can submit one.

Plan of Development template
"this is what we are really looking for"
content design
visual design
web implementation
As a proponent, I want to know who to send that information to so that I can submit a proposal.

"I don't know who to call or what to do?" Broadband website provides a "who to talk to". Some people reach out for "can we meet with you" or others have taken what is on the site and filled out the information so we can review it. They provide information but not the details we need. How do we get the right information?

As a proponent, I want to track the progress of my proposal so that I can estimate when it will be approved

As a proponent I want to estimate approval time so I can prepare for the installation and construction

As a permit administrator, I want to know when proposals are submitted so that I can initiate screening

As a permit administrator, I want to communicate efficiently with the proponent so that I can get the information needed for screening and acceptance

**Comment by dluetger** [comment]
IMO a few tasks associated with this:

- Design a page layout
- Implement a page
- Write the content for each of those three questions (1. How long? 2. What does the process look like overall? 3. What will need to gather?)

**Comment by dluetger** [comment]
Meta-question, what is more useful for us as a team to track the making of things? Is it a user story like this, or is it feature-oriented like "explainer page"?

**Comment by christophermather** [comment]
This info is captured elsewhere on the board. Closing as won't fix.
